// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::transmute_ptr_to_ref)]
#[allow(clippy::upper_case_acronyms)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;

    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("capable_bpf")
            .map("events", false)
            .map("seen", false)
            .map("capable_.rodata", true)
            .map("capable_.bss", true)
            .map("capable.kconfig", true)
            .prog("kprobe__cap_capable");

        builder.build()
    }

    #[derive(Default)]
    pub struct CapableSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl CapableSkelBuilder {
        fn retrieve_maps(
            obj: std::ptr::NonNull<libbpf_sys::bpf_object>,
        ) -> libbpf_rs::Result<std::collections::HashMap<std::string::String, libbpf_rs::OpenMap>>
        {
            let mut maps = std::collections::HashMap::new();
            let mut map = std::ptr::null_mut();
            loop {
                // Get the pointer to the next BPF map
                let map_ptr = {
                    let next_ptr = unsafe { libbpf_sys::bpf_object__next_map(obj.as_ptr(), map) };
                    match std::ptr::NonNull::new(next_ptr) {
                        Some(map_ptr) => map_ptr,
                        None => break,
                    }
                };

                let map_obj = unsafe { libbpf_rs::OpenMap::new(map_ptr) };

                // Add the map to the hashmap
                maps.insert(
                    map_obj
                        .name()
                        .to_str()
                        .ok_or_else(|| {
                            libbpf_rs::Error::from(std::io::Error::new(
                                std::io::ErrorKind::InvalidData,
                                "map has invalid name",
                            ))
                        })?
                        .to_string(),
                    map_obj,
                );
                map = map_ptr.as_ptr();
            }

            Ok(maps)
        }
    }

    impl<'a> SkelBuilder<'a> for CapableSkelBuilder {
        type Output = OpenCapableSkel<'a>;
        fn open(self) -> libbpf_rs::Result<OpenCapableSkel<'a>> {
            let opts = *self.obj_builder.opts();
            self.open_opts(opts)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
        ) -> libbpf_rs::Result<OpenCapableSkel<'a>> {
            let mut skel_config = build_skel_config()?;

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_config.get(), &open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(skel_config.object_ptr())? };
            let maps = Self::retrieve_maps(libbpf_rs::AsRawLibbpf::as_libbpf_object(&obj))?;

            #[allow(unused_mut)]
            let mut skel = OpenCapableSkel {
                obj,
                maps,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    pub struct OpenCapableMapsMut<'a> {
        inner: &'a mut std::collections::HashMap<std::string::String, libbpf_rs::OpenMap>,
    }

    impl OpenCapableMapsMut<'_> {
        pub fn events(&mut self) -> &mut libbpf_rs::OpenMap {
            self.inner.get_mut("events").unwrap()
        }

        pub fn seen(&mut self) -> &mut libbpf_rs::OpenMap {
            self.inner.get_mut("seen").unwrap()
        }

        pub fn rodata(&mut self) -> &mut libbpf_rs::OpenMap {
            self.inner.get_mut("capable_.rodata").unwrap()
        }

        pub fn bss(&mut self) -> &mut libbpf_rs::OpenMap {
            self.inner.get_mut("capable_.bss").unwrap()
        }

        pub fn kconfig(&mut self) -> &mut libbpf_rs::OpenMap {
            self.inner.get_mut("capable.kconfig").unwrap()
        }
    }

    pub struct OpenCapableMaps<'a> {
        inner: &'a std::collections::HashMap<std::string::String, libbpf_rs::OpenMap>,
    }

    impl OpenCapableMaps<'_> {
        pub fn events(&self) -> &libbpf_rs::OpenMap {
            self.inner.get("events").unwrap()
        }

        pub fn seen(&self) -> &libbpf_rs::OpenMap {
            self.inner.get("seen").unwrap()
        }

        pub fn rodata(&self) -> &libbpf_rs::OpenMap {
            self.inner.get("capable_.rodata").unwrap()
        }

        pub fn bss(&self) -> &libbpf_rs::OpenMap {
            self.inner.get("capable_.bss").unwrap()
        }

        pub fn kconfig(&self) -> &libbpf_rs::OpenMap {
            self.inner.get("capable.kconfig").unwrap()
        }
    }

    pub struct OpenCapableProgs<'a> {
        inner: &'a libbpf_rs::OpenObject,
    }

    impl OpenCapableProgs<'_> {
        pub fn kprobe__cap_capable(&self) -> &libbpf_rs::OpenProgram {
            self.inner.prog("kprobe__cap_capable").unwrap()
        }
    }

    pub struct OpenCapableProgsMut<'a> {
        inner: &'a mut libbpf_rs::OpenObject,
    }

    impl OpenCapableProgsMut<'_> {
        pub fn kprobe__cap_capable(&mut self) -> &mut libbpf_rs::OpenProgram {
            self.inner.prog_mut("kprobe__cap_capable").unwrap()
        }
    }

    pub mod capable_types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {
            pub tool_config: __anon_1,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub tgid: u32,
            pub verbose: std::mem::MaybeUninit<bool>,
            pub unique_type: std::mem::MaybeUninit<uniqueness>,
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                __anon_1 {
                    tgid: u32::default(),
                    verbose: std::mem::MaybeUninit::new(bool::default()),
                    unique_type: std::mem::MaybeUninit::new(uniqueness::default()),
                }
            }
        }
        #[derive(Debug, Copy, Clone, Default, PartialEq, Eq)]
        #[repr(u32)]
        pub enum uniqueness {
            #[default]
            UNQ_OFF = 0,
            UNQ_PID = 1,
            UNQ_CGROUP = 2,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct bss {
            pub _event: event,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct event {
            pub tgid: u32,
            pub pid: i32,
            pub uid: u32,
            pub cap: i32,
            pub audit: i32,
            pub insetid: i32,
            pub comm: [u8; 16],
            pub kernel_stack_id: i32,
            pub user_stack_id: i32,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct kconfig {
            pub LINUX_KERNEL_VERSION: i32,
        }

        #[derive(Debug, Clone)]
        #[repr(C)]
        pub struct struct_ops {}

        impl struct_ops {}
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct unique_key {
            pub cap: i32,
            pub tgid: u32,
            pub cgroupid: u64,
        }
    }

    pub struct OpenCapableSkel<'a> {
        pub obj: libbpf_rs::OpenObject,
        maps: std::collections::HashMap<std::string::String, libbpf_rs::OpenMap>,
        pub struct_ops: capable_types::struct_ops,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'a>,
    }

    impl<'a> OpenSkel for OpenCapableSkel<'a> {
        type Output = CapableSkel<'a>;
        fn load(mut self) -> libbpf_rs::Result<CapableSkel<'a>> {
            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(self.skel_config.get()) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj = unsafe { libbpf_rs::Object::from_ptr(self.obj.take_ptr())? };
            let maps = self
                .maps
                .into_iter()
                .map(|(k, v)| {
                    // SAFETY: The `bpf_map` has been validated before and has
                    //         been loaded.
                    let v = unsafe { libbpf_rs::Map::new(v.into_libbpf_object()) };
                    Ok((k, v))
                })
                .collect::<libbpf_rs::Result<_, libbpf_rs::Error>>()?;

            Ok(CapableSkel {
                obj,
                maps,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: CapableLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            &self.obj
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            &mut self.obj
        }
    }
    impl OpenCapableSkel<'_> {
        pub fn progs_mut(&mut self) -> OpenCapableProgsMut<'_> {
            OpenCapableProgsMut {
                inner: &mut self.obj,
            }
        }

        pub fn progs(&self) -> OpenCapableProgs<'_> {
            OpenCapableProgs { inner: &self.obj }
        }

        pub fn maps_mut(&mut self) -> OpenCapableMapsMut<'_> {
            OpenCapableMapsMut {
                inner: &mut self.maps,
            }
        }

        pub fn maps(&self) -> OpenCapableMaps<'_> {
            OpenCapableMaps { inner: &self.maps }
        }

        pub fn rodata_raw(&self) -> *const capable_types::rodata {
            self.skel_config
                .map_mmap_ptr(2)
                .unwrap()
                .cast::<capable_types::rodata>()
        }

        pub fn rodata(&self) -> &capable_types::rodata {
            unsafe { &*self.rodata_raw() }
        }

        pub fn rodata_mut_raw(&mut self) -> *mut capable_types::rodata {
            self.skel_config
                .map_mmap_ptr_mut(2)
                .unwrap()
                .cast::<capable_types::rodata>()
        }

        pub fn rodata_mut(&mut self) -> &mut capable_types::rodata {
            unsafe { &mut *self.rodata_mut_raw() }
        }

        pub fn bss_raw(&self) -> *const capable_types::bss {
            self.skel_config
                .map_mmap_ptr(3)
                .unwrap()
                .cast::<capable_types::bss>()
        }

        pub fn bss(&self) -> &capable_types::bss {
            unsafe { &*self.bss_raw() }
        }

        pub fn bss_mut_raw(&mut self) -> *mut capable_types::bss {
            self.skel_config
                .map_mmap_ptr_mut(3)
                .unwrap()
                .cast::<capable_types::bss>()
        }

        pub fn bss_mut(&mut self) -> &mut capable_types::bss {
            unsafe { &mut *self.bss_mut_raw() }
        }

        pub fn kconfig_raw(&self) -> *const capable_types::kconfig {
            self.skel_config
                .map_mmap_ptr(4)
                .unwrap()
                .cast::<capable_types::kconfig>()
        }

        pub fn kconfig(&self) -> &capable_types::kconfig {
            unsafe { &*self.kconfig_raw() }
        }

        pub fn kconfig_mut_raw(&mut self) -> *mut capable_types::kconfig {
            self.skel_config
                .map_mmap_ptr_mut(4)
                .unwrap()
                .cast::<capable_types::kconfig>()
        }

        pub fn kconfig_mut(&mut self) -> &mut capable_types::kconfig {
            unsafe { &mut *self.kconfig_mut_raw() }
        }
    }

    pub struct CapableMapsMut<'a> {
        inner: &'a mut std::collections::HashMap<std::string::String, libbpf_rs::Map>,
    }

    impl CapableMapsMut<'_> {
        pub fn events(&mut self) -> &mut libbpf_rs::Map {
            self.inner.get_mut("events").unwrap()
        }

        pub fn seen(&mut self) -> &mut libbpf_rs::Map {
            self.inner.get_mut("seen").unwrap()
        }

        pub fn rodata(&mut self) -> &mut libbpf_rs::Map {
            self.inner.get_mut("capable_.rodata").unwrap()
        }

        pub fn bss(&mut self) -> &mut libbpf_rs::Map {
            self.inner.get_mut("capable_.bss").unwrap()
        }

        pub fn kconfig(&mut self) -> &mut libbpf_rs::Map {
            self.inner.get_mut("capable.kconfig").unwrap()
        }
    }

    pub struct CapableMaps<'a> {
        inner: &'a std::collections::HashMap<std::string::String, libbpf_rs::Map>,
    }

    impl CapableMaps<'_> {
        pub fn events(&self) -> &libbpf_rs::Map {
            self.inner.get("events").unwrap()
        }

        pub fn seen(&self) -> &libbpf_rs::Map {
            self.inner.get("seen").unwrap()
        }

        pub fn rodata(&self) -> &libbpf_rs::Map {
            self.inner.get("capable_.rodata").unwrap()
        }

        pub fn bss(&self) -> &libbpf_rs::Map {
            self.inner.get("capable_.bss").unwrap()
        }

        pub fn kconfig(&self) -> &libbpf_rs::Map {
            self.inner.get("capable.kconfig").unwrap()
        }
    }

    pub struct CapableProgs<'a> {
        inner: &'a libbpf_rs::Object,
    }

    impl CapableProgs<'_> {
        pub fn kprobe__cap_capable(&self) -> &libbpf_rs::Program {
            self.inner.prog("kprobe__cap_capable").unwrap()
        }
    }

    pub struct CapableProgsMut<'a> {
        inner: &'a mut libbpf_rs::Object,
    }

    impl CapableProgsMut<'_> {
        pub fn kprobe__cap_capable(&mut self) -> &mut libbpf_rs::Program {
            self.inner.prog_mut("kprobe__cap_capable").unwrap()
        }
    }

    #[derive(Default)]
    pub struct CapableLinks {
        pub kprobe__cap_capable: Option<libbpf_rs::Link>,
    }

    pub struct CapableSkel<'a> {
        pub obj: libbpf_rs::Object,
        maps: std::collections::HashMap<std::string::String, libbpf_rs::Map>,
        struct_ops: capable_types::struct_ops,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'a>,
        pub links: CapableLinks,
    }

    unsafe impl Send for CapableSkel<'_> {}
    unsafe impl Sync for CapableSkel<'_> {}

    impl Skel for CapableSkel<'_> {
        fn object(&self) -> &libbpf_rs::Object {
            &self.obj
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            &mut self.obj
        }

        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(self.skel_config.get()) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = CapableLinks {
                kprobe__cap_capable: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl CapableSkel<'_> {
        pub fn progs_mut(&mut self) -> CapableProgsMut<'_> {
            CapableProgsMut {
                inner: &mut self.obj,
            }
        }

        pub fn progs(&self) -> CapableProgs<'_> {
            CapableProgs { inner: &self.obj }
        }

        pub fn maps_mut(&mut self) -> CapableMapsMut<'_> {
            CapableMapsMut {
                inner: &mut self.maps,
            }
        }

        pub fn maps(&self) -> CapableMaps<'_> {
            CapableMaps { inner: &self.maps }
        }

        pub fn struct_ops_raw(&self) -> *const capable_types::struct_ops {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &capable_types::struct_ops {
            &self.struct_ops
        }

        pub fn rodata_raw(&self) -> *const capable_types::rodata {
            self.skel_config
                .map_mmap_ptr(2)
                .unwrap()
                .cast::<capable_types::rodata>()
        }

        pub fn rodata(&self) -> &capable_types::rodata {
            unsafe { &*self.rodata_raw() }
        }

        pub fn bss_raw(&self) -> *const capable_types::bss {
            self.skel_config
                .map_mmap_ptr(3)
                .unwrap()
                .cast::<capable_types::bss>()
        }

        pub fn bss(&self) -> &capable_types::bss {
            unsafe { &*self.bss_raw() }
        }

        pub fn bss_mut_raw(&mut self) -> *mut capable_types::bss {
            self.skel_config
                .map_mmap_ptr_mut(3)
                .unwrap()
                .cast::<capable_types::bss>()
        }

        pub fn bss_mut(&mut self) -> &mut capable_types::bss {
            unsafe { &mut *self.bss_mut_raw() }
        }

        pub fn kconfig_raw(&self) -> *const capable_types::kconfig {
            self.skel_config
                .map_mmap_ptr(4)
                .unwrap()
                .cast::<capable_types::kconfig>()
        }

        pub fn kconfig(&self) -> &capable_types::kconfig {
            unsafe { &*self.kconfig_raw() }
        }
    }

    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 11, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97,
        98, 0, 107, 112, 114, 111, 98, 101, 47, 99, 97, 112, 95, 99, 97, 112, 97, 98, 108, 101, 0,
        46, 114, 111, 100, 97, 116, 97, 0, 46, 98, 115, 115, 0, 108, 105, 99, 101, 110, 115, 101,
        0, 46, 109, 97, 112, 115, 0, 99, 97, 112, 97, 98, 108, 101, 46, 98, 112, 102, 46, 99, 0,
        76, 66, 66, 48, 95, 50, 0, 76, 66, 66, 48, 95, 52, 0, 76, 66, 66, 48, 95, 49, 51, 0, 76,
        66, 66, 48, 95, 54, 0, 76, 66, 66, 48, 95, 49, 50, 0, 76, 66, 66, 48, 95, 57, 0, 76, 66,
        66, 48, 95, 49, 48, 0, 107, 112, 114, 111, 98, 101, 95, 95, 99, 97, 112, 95, 99, 97, 112,
        97, 98, 108, 101, 0, 76, 73, 78, 85, 88, 95, 75, 69, 82, 78, 69, 76, 95, 86, 69, 82, 83,
        73, 79, 78, 0, 116, 111, 111, 108, 95, 99, 111, 110, 102, 105, 103, 0, 115, 101, 101, 110,
        0, 101, 118, 101, 110, 116, 115, 0, 95, 101, 118, 101, 110, 116, 0, 76, 73, 67, 69, 78, 83,
        69, 0, 46, 114, 101, 108, 107, 112, 114, 111, 98, 101, 47, 99, 97, 112, 95, 99, 97, 112,
        97, 98, 108, 101, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 63, 0, 0, 0, 4, 0, 241,
        255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 77, 0, 0, 0, 0, 0, 3, 0, 168, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 84, 0, 0, 0, 0, 0, 3, 0, 232, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 91, 0, 0, 0, 0, 0, 3, 0, 224, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99, 0, 0, 0,
        0, 0, 3, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 106, 0, 0, 0, 0, 0, 3, 0, 120,
        2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 114, 0, 0, 0, 0, 0, 3, 0, 240, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 121, 0, 0, 0, 0, 0, 3, 0, 248, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 129, 0, 0, 0, 18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 2, 0, 0, 0, 0, 0, 0,
        149, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 170, 0, 0, 0,
        17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 182, 0, 0, 0, 17, 0, 7, 0,
        24, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 187, 0, 0, 0, 17, 0, 7, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 194, 0, 0, 0, 17, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 0,
        0, 0, 0, 0, 0, 0, 201, 0, 0, 0, 17, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0,
        0, 24, 8, 0, 0, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 121, 25, 88, 0, 0, 0, 0, 0,
        123, 26, 168, 255, 0, 0, 0, 0, 121, 17, 96, 0, 0, 0, 0, 0, 123, 26, 176, 255, 0, 0, 0, 0,
        133, 0, 0, 0, 14, 0, 0, 0, 191, 6, 0, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 97, 17, 0, 0, 0, 0, 0, 0, 103, 1, 0, 0, 32, 0, 0, 0, 199, 1, 0, 0, 32, 0, 0, 0,
        183, 2, 0, 0, 0, 1, 5, 0, 109, 18, 6, 0, 0, 0, 0, 0, 191, 152, 0, 0, 0, 0, 0, 0, 119, 8, 0,
        0, 2, 0, 0, 0, 87, 8, 0, 0, 1, 0, 0, 0, 167, 9, 0, 0, 255, 255, 255, 255, 119, 9, 0, 0, 1,
        0, 0, 0, 87, 9, 0, 0, 1, 0, 0, 0, 191, 103, 0, 0, 0, 0, 0, 0, 119, 7, 0, 0, 32, 0, 0, 0,
        24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 18, 0, 0, 0, 0, 0, 0, 21, 2, 2, 0, 0,
        0, 0, 0, 97, 18, 0, 0, 0, 0, 0, 0, 93, 114, 63, 0, 0, 0, 0, 0, 113, 17, 4, 0, 0, 0, 0, 0,
        191, 146, 0, 0, 0, 0, 0, 0, 103, 2, 0, 0, 32, 0, 0, 0, 119, 2, 0, 0, 32, 0, 0, 0, 85, 2, 1,
        0, 0, 0, 0, 0, 21, 1, 57, 0, 0, 0, 0, 0, 133, 0, 0, 0, 15, 0, 0, 0, 183, 1, 0, 0, 0, 0, 0,
        0, 99, 26, 236, 255, 0, 0, 0, 0, 99, 26, 232, 255, 0, 0, 0, 0, 99, 26, 244, 255, 0, 0, 0,
        0, 99, 26, 240, 255, 0, 0, 0, 0, 99, 26, 252, 255, 0, 0, 0, 0, 99, 26, 248, 255, 0, 0, 0,
        0, 99, 138, 228, 255, 0, 0, 0, 0, 99, 154, 224, 255, 0, 0, 0, 0, 121, 164, 176, 255, 0, 0,
        0, 0, 99, 74, 220, 255, 0, 0, 0, 0, 99, 10, 216, 255, 0, 0, 0, 0, 99, 106, 212, 255, 0, 0,
        0, 0, 99, 122, 208, 255, 0, 0, 0, 0, 24, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97,
        35, 8, 0, 0, 0, 0, 0, 21, 3, 25, 0, 0, 0, 0, 0, 123, 26, 200, 255, 0, 0, 0, 0, 99, 26, 196,
        255, 0, 0, 0, 0, 99, 74, 192, 255, 0, 0, 0, 0, 97, 33, 8, 0, 0, 0, 0, 0, 85, 1, 3, 0, 2, 0,
        0, 0, 133, 0, 0, 0, 80, 0, 0, 0, 123, 10, 200, 255, 0, 0, 0, 0, 5, 0, 1, 0, 0, 0, 0, 0, 99,
        122, 196, 255, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 192, 255, 255, 255, 24,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 1, 0, 0, 0, 85, 0, 23, 0, 0, 0,
        0, 0, 183, 1, 0, 0, 0, 0, 0, 0, 123, 26, 184, 255, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0,
        7, 2, 0, 0, 192, 255, 255, 255, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 184, 255, 255, 255,
        24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 4, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 2,
        0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 232, 255, 255, 255, 183, 2, 0, 0, 16, 0,
        0, 0, 133, 0, 0, 0, 16, 0, 0, 0, 191, 164, 0, 0, 0, 0, 0, 0, 7, 4, 0, 0, 208, 255, 255,
        255, 121, 161, 168, 255, 0, 0, 0, 0, 24, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24,
        3, 0, 0, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 183, 5, 0, 0, 48, 0, 0, 0, 133, 0, 0,
        0, 25, 0, 0, 0, 183, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 71, 80, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 11, 0, 0, 0, 184, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 12, 0, 0, 0, 144, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 12, 0, 0, 0, 8, 2, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 13, 0, 0, 0, 88, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 13, 0, 0, 0, 176, 2,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 14, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 104, 5,
        0, 0, 104, 5, 0, 0, 247, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 4, 0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 4,
        0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 4, 24, 0, 0,
        0, 25, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 1, 0, 0, 0, 64, 0, 0, 0, 39, 0, 0, 0,
        1, 0, 0, 0, 128, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0, 14, 5, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 2, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4,
        0, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 12, 0, 0, 0, 57, 0, 0, 0, 3, 0, 0, 4, 16, 0,
        0, 0, 68, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 72, 0, 0, 0, 13, 0, 0, 0, 32, 0, 0, 0, 77, 0, 0,
        0, 16, 0, 0, 0, 64, 0, 0, 0, 86, 0, 0, 0, 0, 0, 0, 8, 14, 0, 0, 0, 90, 0, 0, 0, 0, 0, 0, 8,
        15, 0, 0, 0, 96, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 109, 0, 0, 0, 0, 0, 0, 8,
        17, 0, 0, 0, 113, 0, 0, 0, 0, 0, 0, 8, 18, 0, 0, 0, 119, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0,
        64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 16, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 32, 0, 0, 0, 25,
        0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 138, 0, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 150, 0, 0, 0, 11,
        0, 0, 0, 128, 0, 0, 0, 154, 0, 0, 0, 19, 0, 0, 0, 192, 0, 0, 0, 160, 0, 0, 0, 0, 0, 0, 14,
        20, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 23, 0, 0, 0, 165, 0, 0, 0, 21, 0, 0, 4,
        168, 0, 0, 0, 173, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 177, 0, 0, 0, 24, 0, 0, 0, 64, 0, 0,
        0, 181, 0, 0, 0, 24, 0, 0, 0, 128, 0, 0, 0, 185, 0, 0, 0, 24, 0, 0, 0, 192, 0, 0, 0, 189,
        0, 0, 0, 24, 0, 0, 0, 0, 1, 0, 0, 192, 0, 0, 0, 24, 0, 0, 0, 64, 1, 0, 0, 195, 0, 0, 0, 24,
        0, 0, 0, 128, 1, 0, 0, 199, 0, 0, 0, 24, 0, 0, 0, 192, 1, 0, 0, 203, 0, 0, 0, 24, 0, 0, 0,
        0, 2, 0, 0, 206, 0, 0, 0, 24, 0, 0, 0, 64, 2, 0, 0, 209, 0, 0, 0, 24, 0, 0, 0, 128, 2, 0,
        0, 212, 0, 0, 0, 24, 0, 0, 0, 192, 2, 0, 0, 215, 0, 0, 0, 24, 0, 0, 0, 0, 3, 0, 0, 218, 0,
        0, 0, 24, 0, 0, 0, 64, 3, 0, 0, 221, 0, 0, 0, 24, 0, 0, 0, 128, 3, 0, 0, 224, 0, 0, 0, 24,
        0, 0, 0, 192, 3, 0, 0, 232, 0, 0, 0, 24, 0, 0, 0, 0, 4, 0, 0, 235, 0, 0, 0, 24, 0, 0, 0,
        64, 4, 0, 0, 238, 0, 0, 0, 24, 0, 0, 0, 128, 4, 0, 0, 244, 0, 0, 0, 24, 0, 0, 0, 192, 4, 0,
        0, 247, 0, 0, 0, 24, 0, 0, 0, 0, 5, 0, 0, 250, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 13, 2, 0, 0, 0, 8, 1, 0, 0, 22, 0, 0, 0, 12, 1, 0, 0, 1, 0, 0, 12,
        25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 28, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 29, 0, 0, 0, 0,
        0, 0, 0, 3, 0, 0, 4, 12, 0, 0, 0, 72, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0, 32, 1, 0, 0, 32, 0,
        0, 0, 32, 0, 0, 0, 40, 1, 0, 0, 34, 0, 0, 0, 64, 0, 0, 0, 52, 1, 0, 0, 0, 0, 0, 8, 31, 0,
        0, 0, 58, 1, 0, 0, 0, 0, 0, 8, 15, 0, 0, 0, 75, 1, 0, 0, 0, 0, 0, 8, 33, 0, 0, 0, 80, 1, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 4, 86, 1, 0, 0, 3, 0, 0, 6, 4, 0, 0, 0, 97, 1, 0, 0, 0,
        0, 0, 0, 105, 1, 0, 0, 1, 0, 0, 0, 113, 1, 0, 0, 2, 0, 0, 0, 124, 1, 0, 0, 0, 0, 0, 14, 27,
        0, 0, 0, 1, 0, 0, 0, 136, 1, 0, 0, 9, 0, 0, 4, 48, 0, 0, 0, 72, 0, 0, 0, 30, 0, 0, 0, 0, 0,
        0, 0, 142, 1, 0, 0, 37, 0, 0, 0, 32, 0, 0, 0, 146, 1, 0, 0, 39, 0, 0, 0, 64, 0, 0, 0, 68,
        0, 0, 0, 2, 0, 0, 0, 96, 0, 0, 0, 150, 1, 0, 0, 2, 0, 0, 0, 128, 0, 0, 0, 156, 1, 0, 0, 2,
        0, 0, 0, 160, 0, 0, 0, 164, 1, 0, 0, 44, 0, 0, 0, 192, 0, 0, 0, 169, 1, 0, 0, 2, 0, 0, 0,
        64, 1, 0, 0, 185, 1, 0, 0, 2, 0, 0, 0, 96, 1, 0, 0, 199, 1, 0, 0, 0, 0, 0, 8, 38, 0, 0, 0,
        205, 1, 0, 0, 0, 0, 0, 8, 2, 0, 0, 0, 220, 1, 0, 0, 0, 0, 0, 8, 40, 0, 0, 0, 226, 1, 0, 0,
        0, 0, 0, 8, 15, 0, 0, 0, 243, 1, 0, 0, 0, 0, 0, 8, 42, 0, 0, 0, 246, 1, 0, 0, 0, 0, 0, 8,
        43, 0, 0, 0, 251, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0,
        0, 0, 0, 41, 0, 0, 0, 4, 0, 0, 0, 16, 0, 0, 0, 9, 2, 0, 0, 0, 0, 0, 14, 36, 0, 0, 0, 1, 0,
        0, 0, 16, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0,
        46, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 21, 2, 0, 0, 0, 0, 0, 14, 47, 0, 0, 0, 1, 0, 0, 0, 29,
        2, 0, 0, 0, 0, 0, 14, 2, 0, 0, 0, 2, 0, 0, 0, 192, 5, 0, 0, 1, 0, 0, 15, 12, 0, 0, 0, 35,
        0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 200, 5, 0, 0, 1, 0, 0, 15, 48, 0, 0, 0, 45, 0, 0, 0, 0,
        0, 0, 0, 48, 0, 0, 0, 205, 5, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 48, 0, 0, 0, 0, 0, 0, 0, 4, 0,
        0, 0, 213, 5, 0, 0, 2, 0, 0, 15, 56, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 21, 0,
        0, 0, 24, 0, 0, 0, 32, 0, 0, 0, 219, 5, 0, 0, 1, 0, 0, 15, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0,
        0, 0, 4, 0, 0, 0, 0, 105, 110, 116, 0, 95, 95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95,
        84, 89, 80, 69, 95, 95, 0, 116, 121, 112, 101, 0, 107, 101, 121, 95, 115, 105, 122, 101, 0,
        118, 97, 108, 117, 101, 95, 115, 105, 122, 101, 0, 101, 118, 101, 110, 116, 115, 0, 117,
        110, 105, 113, 117, 101, 95, 107, 101, 121, 0, 99, 97, 112, 0, 116, 103, 105, 100, 0, 99,
        103, 114, 111, 117, 112, 105, 100, 0, 117, 51, 50, 0, 95, 95, 117, 51, 50, 0, 117, 110,
        115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0, 117, 54, 52, 0, 95, 95, 117, 54, 52, 0,
        117, 110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 32, 108, 111, 110, 103, 0,
        109, 97, 120, 95, 101, 110, 116, 114, 105, 101, 115, 0, 107, 101, 121, 0, 118, 97, 108,
        117, 101, 0, 115, 101, 101, 110, 0, 112, 116, 95, 114, 101, 103, 115, 0, 114, 49, 53, 0,
        114, 49, 52, 0, 114, 49, 51, 0, 114, 49, 50, 0, 98, 112, 0, 98, 120, 0, 114, 49, 49, 0,
        114, 49, 48, 0, 114, 57, 0, 114, 56, 0, 97, 120, 0, 99, 120, 0, 100, 120, 0, 115, 105, 0,
        100, 105, 0, 111, 114, 105, 103, 95, 97, 120, 0, 105, 112, 0, 99, 115, 0, 102, 108, 97,
        103, 115, 0, 115, 112, 0, 115, 115, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 108,
        111, 110, 103, 0, 99, 116, 120, 0, 107, 112, 114, 111, 98, 101, 95, 95, 99, 97, 112, 95,
        99, 97, 112, 97, 98, 108, 101, 0, 118, 101, 114, 98, 111, 115, 101, 0, 117, 110, 105, 113,
        117, 101, 95, 116, 121, 112, 101, 0, 103, 105, 100, 95, 116, 0, 95, 95, 107, 101, 114, 110,
        101, 108, 95, 103, 105, 100, 51, 50, 95, 116, 0, 98, 111, 111, 108, 0, 95, 66, 111, 111,
        108, 0, 117, 110, 105, 113, 117, 101, 110, 101, 115, 115, 0, 85, 78, 81, 95, 79, 70, 70, 0,
        85, 78, 81, 95, 80, 73, 68, 0, 85, 78, 81, 95, 67, 71, 82, 79, 85, 80, 0, 116, 111, 111,
        108, 95, 99, 111, 110, 102, 105, 103, 0, 101, 118, 101, 110, 116, 0, 112, 105, 100, 0, 117,
        105, 100, 0, 97, 117, 100, 105, 116, 0, 105, 110, 115, 101, 116, 105, 100, 0, 99, 111, 109,
        109, 0, 107, 101, 114, 110, 101, 108, 95, 115, 116, 97, 99, 107, 95, 105, 100, 0, 117, 115,
        101, 114, 95, 115, 116, 97, 99, 107, 95, 105, 100, 0, 112, 105, 100, 95, 116, 0, 95, 95,
        107, 101, 114, 110, 101, 108, 95, 112, 105, 100, 95, 116, 0, 117, 105, 100, 95, 116, 0, 95,
        95, 107, 101, 114, 110, 101, 108, 95, 117, 105, 100, 51, 50, 95, 116, 0, 117, 56, 0, 95,
        95, 117, 56, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 99, 104, 97, 114, 0, 95, 101,
        118, 101, 110, 116, 0, 99, 104, 97, 114, 0, 76, 73, 67, 69, 78, 83, 69, 0, 76, 73, 78, 85,
        88, 95, 75, 69, 82, 78, 69, 76, 95, 86, 69, 82, 83, 73, 79, 78, 0, 47, 104, 111, 109, 101,
        47, 109, 117, 101, 108, 108, 101, 114, 100, 47, 108, 111, 99, 97, 108, 47, 111, 112, 116,
        47, 108, 105, 98, 98, 112, 102, 45, 114, 115, 47, 101, 120, 97, 109, 112, 108, 101, 115,
        47, 99, 97, 112, 97, 98, 108, 101, 47, 115, 114, 99, 47, 98, 112, 102, 47, 99, 97, 112, 97,
        98, 108, 101, 46, 98, 112, 102, 46, 99, 0, 105, 110, 116, 32, 66, 80, 70, 95, 75, 80, 82,
        79, 66, 69, 40, 107, 112, 114, 111, 98, 101, 95, 95, 99, 97, 112, 95, 99, 97, 112, 97, 98,
        108, 101, 44, 32, 99, 111, 110, 115, 116, 32, 115, 116, 114, 117, 99, 116, 32, 99, 114,
        101, 100, 32, 42, 99, 114, 101, 100, 44, 0, 9, 117, 54, 52, 32, 95, 95, 112, 105, 100, 95,
        116, 103, 105, 100, 32, 61, 32, 98, 112, 102, 95, 103, 101, 116, 95, 99, 117, 114, 114,
        101, 110, 116, 95, 112, 105, 100, 95, 116, 103, 105, 100, 40, 41, 59, 0, 9, 105, 102, 32,
        40, 76, 73, 78, 85, 88, 95, 75, 69, 82, 78, 69, 76, 95, 86, 69, 82, 83, 73, 79, 78, 32, 62,
        61, 32, 75, 69, 82, 78, 69, 76, 95, 86, 69, 82, 83, 73, 79, 78, 40, 53, 44, 32, 49, 44, 32,
        48, 41, 41, 32, 123, 0, 9, 9, 105, 110, 115, 101, 116, 105, 100, 32, 61, 32, 40, 99, 97,
        112, 95, 111, 112, 116, 32, 38, 32, 48, 98, 49, 48, 48, 41, 32, 33, 61, 32, 48, 59, 0, 9,
        9, 97, 117, 100, 105, 116, 32, 61, 32, 40, 99, 97, 112, 95, 111, 112, 116, 32, 38, 32, 48,
        98, 49, 48, 41, 32, 61, 61, 32, 48, 59, 0, 9, 105, 102, 32, 40, 116, 111, 111, 108, 95, 99,
        111, 110, 102, 105, 103, 46, 116, 103, 105, 100, 32, 38, 38, 32, 116, 103, 105, 100, 32,
        33, 61, 32, 116, 111, 111, 108, 95, 99, 111, 110, 102, 105, 103, 46, 116, 103, 105, 100,
        41, 32, 123, 0, 9, 105, 102, 32, 40, 33, 116, 111, 111, 108, 95, 99, 111, 110, 102, 105,
        103, 46, 118, 101, 114, 98, 111, 115, 101, 32, 38, 38, 32, 97, 117, 100, 105, 116, 32, 61,
        61, 32, 48, 41, 32, 123, 0, 9, 117, 105, 100, 95, 116, 32, 117, 105, 100, 32, 61, 32, 98,
        112, 102, 95, 103, 101, 116, 95, 99, 117, 114, 114, 101, 110, 116, 95, 117, 105, 100, 95,
        103, 105, 100, 40, 41, 59, 0, 9, 115, 116, 114, 117, 99, 116, 32, 101, 118, 101, 110, 116,
        32, 101, 118, 101, 110, 116, 32, 61, 32, 123, 0, 9, 105, 102, 32, 40, 116, 111, 111, 108,
        95, 99, 111, 110, 102, 105, 103, 46, 117, 110, 105, 113, 117, 101, 95, 116, 121, 112, 101,
        41, 32, 123, 0, 9, 9, 115, 116, 114, 117, 99, 116, 32, 117, 110, 105, 113, 117, 101, 95,
        107, 101, 121, 32, 107, 101, 121, 32, 61, 32, 123, 46, 99, 97, 112, 32, 61, 32, 99, 97,
        112, 125, 59, 0, 9, 9, 105, 102, 32, 40, 116, 111, 111, 108, 95, 99, 111, 110, 102, 105,
        103, 46, 117, 110, 105, 113, 117, 101, 95, 116, 121, 112, 101, 32, 61, 61, 32, 85, 78, 81,
        95, 67, 71, 82, 79, 85, 80, 41, 32, 123, 0, 9, 9, 9, 107, 101, 121, 46, 99, 103, 114, 111,
        117, 112, 105, 100, 32, 61, 32, 98, 112, 102, 95, 103, 101, 116, 95, 99, 117, 114, 114,
        101, 110, 116, 95, 99, 103, 114, 111, 117, 112, 95, 105, 100, 40, 41, 59, 0, 9, 9, 9, 107,
        101, 121, 46, 116, 103, 105, 100, 32, 61, 32, 116, 103, 105, 100, 59, 0, 9, 9, 105, 102,
        32, 40, 98, 112, 102, 95, 109, 97, 112, 95, 108, 111, 111, 107, 117, 112, 95, 101, 108,
        101, 109, 40, 38, 115, 101, 101, 110, 44, 32, 38, 107, 101, 121, 41, 32, 33, 61, 32, 78,
        85, 76, 76, 41, 32, 123, 0, 9, 9, 117, 54, 52, 32, 122, 101, 114, 111, 32, 61, 32, 48, 59,
        0, 9, 9, 98, 112, 102, 95, 109, 97, 112, 95, 117, 112, 100, 97, 116, 101, 95, 101, 108,
        101, 109, 40, 38, 115, 101, 101, 110, 44, 32, 38, 107, 101, 121, 44, 32, 38, 122, 101, 114,
        111, 44, 32, 48, 41, 59, 0, 9, 98, 112, 102, 95, 103, 101, 116, 95, 99, 117, 114, 114, 101,
        110, 116, 95, 99, 111, 109, 109, 40, 38, 101, 118, 101, 110, 116, 46, 99, 111, 109, 109,
        44, 32, 115, 105, 122, 101, 111, 102, 40, 101, 118, 101, 110, 116, 46, 99, 111, 109, 109,
        41, 41, 59, 0, 9, 98, 112, 102, 95, 112, 101, 114, 102, 95, 101, 118, 101, 110, 116, 95,
        111, 117, 116, 112, 117, 116, 40, 99, 116, 120, 44, 32, 38, 101, 118, 101, 110, 116, 115,
        44, 32, 66, 80, 70, 95, 70, 95, 67, 85, 82, 82, 69, 78, 84, 95, 67, 80, 85, 44, 32, 38,
        101, 118, 101, 110, 116, 44, 32, 115, 105, 122, 101, 111, 102, 40, 101, 118, 101, 110, 116,
        41, 41, 59, 0, 48, 58, 49, 49, 0, 48, 58, 49, 50, 0, 46, 114, 111, 100, 97, 116, 97, 0, 46,
        98, 115, 115, 0, 108, 105, 99, 101, 110, 115, 101, 0, 46, 109, 97, 112, 115, 0, 46, 107,
        99, 111, 110, 102, 105, 103, 0, 107, 112, 114, 111, 98, 101, 47, 99, 97, 112, 95, 99, 97,
        112, 97, 98, 108, 101, 0, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 20, 0,
        0, 0, 12, 2, 0, 0, 32, 2, 0, 0, 44, 0, 0, 0, 8, 0, 0, 0, 228, 5, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 26, 0, 0, 0, 16, 0, 0, 0, 228, 5, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 50, 2, 0, 0, 124, 2, 0,
        0, 0, 152, 1, 0, 16, 0, 0, 0, 50, 2, 0, 0, 124, 2, 0, 0, 5, 152, 1, 0, 40, 0, 0, 0, 50, 2,
        0, 0, 185, 2, 0, 0, 19, 188, 0, 0, 64, 0, 0, 0, 50, 2, 0, 0, 231, 2, 0, 0, 6, 212, 0, 0,
        112, 0, 0, 0, 50, 2, 0, 0, 231, 2, 0, 0, 6, 212, 0, 0, 120, 0, 0, 0, 50, 2, 0, 0, 31, 3, 0,
        0, 31, 224, 0, 0, 144, 0, 0, 0, 50, 2, 0, 0, 67, 3, 0, 0, 28, 220, 0, 0, 168, 0, 0, 0, 50,
        2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 184, 0, 0, 0, 50, 2, 0, 0, 100, 3, 0, 0, 18, 248, 0, 0,
        208, 0, 0, 0, 50, 2, 0, 0, 100, 3, 0, 0, 23, 248, 0, 0, 216, 0, 0, 0, 50, 2, 0, 0, 100, 3,
        0, 0, 46, 248, 0, 0, 224, 0, 0, 0, 50, 2, 0, 0, 100, 3, 0, 0, 6, 248, 0, 0, 232, 0, 0, 0,
        50, 2, 0, 0, 153, 3, 0, 0, 27, 8, 1, 0, 24, 1, 0, 0, 50, 2, 0, 0, 196, 3, 0, 0, 14, 24, 1,
        0, 40, 1, 0, 0, 50, 2, 0, 0, 236, 3, 0, 0, 23, 32, 1, 0, 144, 1, 0, 0, 50, 2, 0, 0, 4, 4,
        0, 0, 18, 64, 1, 0, 168, 1, 0, 0, 50, 2, 0, 0, 4, 4, 0, 0, 6, 64, 1, 0, 176, 1, 0, 0, 50,
        2, 0, 0, 36, 4, 0, 0, 27, 68, 1, 0, 200, 1, 0, 0, 50, 2, 0, 0, 76, 4, 0, 0, 19, 72, 1, 0,
        208, 1, 0, 0, 50, 2, 0, 0, 76, 4, 0, 0, 7, 72, 1, 0, 216, 1, 0, 0, 50, 2, 0, 0, 123, 4, 0,
        0, 19, 76, 1, 0, 224, 1, 0, 0, 50, 2, 0, 0, 123, 4, 0, 0, 17, 76, 1, 0, 240, 1, 0, 0, 50,
        2, 0, 0, 170, 4, 0, 0, 13, 84, 1, 0, 0, 2, 0, 0, 50, 2, 0, 0, 190, 4, 0, 0, 7, 96, 1, 0,
        32, 2, 0, 0, 50, 2, 0, 0, 190, 4, 0, 0, 7, 96, 1, 0, 48, 2, 0, 0, 50, 2, 0, 0, 240, 4, 0,
        0, 7, 108, 1, 0, 88, 2, 0, 0, 50, 2, 0, 0, 0, 5, 0, 0, 3, 112, 1, 0, 120, 2, 0, 0, 50, 2,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 136, 2, 0, 0, 50, 2, 0, 0, 46, 5, 0, 0, 2, 124, 1, 0, 160, 2,
        0, 0, 50, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 168, 2, 0, 0, 50, 2, 0, 0, 102, 5, 0, 0, 2, 128,
        1, 0, 224, 2, 0, 0, 50, 2, 0, 0, 124, 2, 0, 0, 5, 152, 1, 0, 16, 0, 0, 0, 228, 5, 0, 0, 2,
        0, 0, 0, 16, 0, 0, 0, 23, 0, 0, 0, 182, 5, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 23, 0, 0, 0, 187,
        5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 246, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 56, 1, 0, 0, 0, 0, 0, 0, 152, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1,
        0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 208, 2, 0, 0, 0, 0, 0, 0, 240, 2,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        36, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 5, 0, 0, 0,
        0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 44, 0, 0, 0, 8, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        204, 5, 0, 0, 0, 0, 0, 0, 48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 204, 5, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 57, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 208, 5, 0, 0, 0, 0, 0, 0, 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 209, 0, 0, 0, 9, 0, 0, 0, 64,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 6, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 0, 0, 0,
        0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 232, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 104, 6, 0, 0, 0, 0, 0, 0, 119,
        11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 237, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 224, 17, 0, 0,
        0, 0, 0, 0, 108, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0,
    ];
}
