name: Publish

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Publish libbpf-rs
      run: cd libbpf-rs && cargo publish --no-verify --token "${CRATES_IO_TOKEN}"
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    - name: Publish libbpf-cargo
      run: cd libbpf-cargo && cargo publish --no-verify --token "${CRATES_IO_TOKEN}"
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
